# Import Data

In [ ]:
# Import Library yang Diperlukan
!pip install transformers
!pip install pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os
import string
import warnings
from tqdm.auto import tqdm
import torch
from transformers import BertTokenizer, BertForSequenceClassification, get_scheduler
from torch.utils.data import DataLoader, Dataset
warnings.filterwarnings('ignore')

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.3.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Skripsi/makan_siang_gratis_10.csv')
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2.003730e+18,Wed Dec 24 23:59:15 +0000 2025,0,@DS_yantie Lah itu MBG apakabar??? Pak pak,2.003980e+18,NaN,DS_yantie,in,NaN,0,0,0,https://x.com/undefined/status/200397881329920...,7.998670e+17,NaN
1,2.003980e+18,Wed Dec 24 23:58:53 +0000 2025,0,MBG anak sehat Indonesia hebat #FaktaIndonesia...,2.003980e+18,https://pbs.twimg.com/media/G8-QBmJb0AUqtl5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/200397871919997...,1.615860e+18,NaN
2,2.003980e+18,Wed Dec 24 23:58:23 +0000 2025,0,Pentingnya program MBG untuk masa depan #Fakta...,2.003980e+18,https://pbs.twimg.com/media/G8-P6E2bQAAUbq-.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/200397859238939...,1.615860e+18,NaN
3,2.003980e+18,Wed Dec 24 23:58:09 +0000 2025,0,MBG adalah langkah nyata membangun generasi se...,2.003980e+18,https://pbs.twimg.com/media/G8-P26JbYAA7nnM.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/200397853604726...,1.615860e+18,NaN
4,2.003960e+18,Wed Dec 24 23:58:09 +0000 2025,1,@komaria_cocom MBG anakku loh kak bikin ngelus...,2.003980e+18,NaN,komaria_cocom,in,NaN,0,0,0,https://x.com/undefined/status/200397853383682...,1.971780e+18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7799,1.928020e+18,Thu May 29 09:29:27 +0000 2025,0,Naahh!! Dengan adanya program MBG anak-anak ga...,1.928020e+18,https://pbs.twimg.com/media/GsG0v5IaUAQG8Iu.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/192802085395617...,9.926921e+08,NaN
7800,1.927670e+18,Thu May 29 09:29:10 +0000 2025,0,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,1.928020e+18,NaN,ranie__14,in,NaN,0,0,0,https://x.com/undefined/status/192802078443534...,9.380510e+17,NaN
7801,1.928020e+18,Thu May 29 09:28:24 +0000 2025,0,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,1.928020e+18,https://pbs.twimg.com/ext_tw_video_thumb/19280...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/192802059203455...,1.262160e+18,NaN
7802,1.927890e+18,Thu May 29 09:28:12 +0000 2025,0,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,1.928020e+18,NaN,txtdrimedia,in,NaN,0,0,0,https://x.com/undefined/status/192802054057857...,1.590840e+18,NaN
7803,1.928020e+18,Thu May 29 09:27:21 +0000 2025,0,mbg yg baru jalan blm ada setaun itu..?,1.928020e+18,NaN,bublwoo,in,NaN,0,0,0,https://x.com/undefined/status/192802032534360...,1.812910e+18,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7804 entries, 0 to 7803
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      7804 non-null   float64
 1   created_at               7804 non-null   object
 2   favorite_count           7804 non-null   int64
 3   full_text                7804 non-null   object
 4   id_str                   7804 non-null   float64
 5   image_url                1326 non-null   object
 6   in_reply_to_screen_name  4685 non-null   object
 7   lang                     7804 non-null   object
 8   location                 0 non-null      float64
 9   quote_count              7804 non-null   int64
 10  reply_count              7804 non-null   int64
 11  retweet_count            7804 non-null   int64
 12  tweet_url                7804 non-null   object
 13  user_id_str              7804 non-null   float64
 14  username                 0 non-null      float64
dtypes: float64(5), int64(4), object(6)
memory usage: 914.7+ KB

# Data Cleaning

In [ ]:
df.drop(['conversation_id_str','created_at','favorite_count','id_str','image_url','in_reply_to_screen_name','lang','location','quote_count','reply_count','retweet_count','tweet_url','user_id_str','username'],axis=1,inplace=True)
df

                                              full_text
0           @DS_yantie Lah itu MBG apakabar??? Pak pak
1     MBG anak sehat Indonesia hebat #FaktaIndonesia...
2     Pentingnya program MBG untuk masa depan #Fakta...
3     MBG adalah langkah nyata membangun generasi se...
4     @komaria_cocom MBG anakku loh kak bikin ngelus...
...                                                 ...
7799  Naahh!! Dengan adanya program MBG anak-anak ga...
7800  @ranie__14 @endahm7 @Dandhy_Laksono yang dimak...
7801  Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...
7802  @txtdrimedia Yg dikasih MBG jutaan siswa kalan...
7803            mbg yg baru jalan blm ada setaun itu..?

[7804 rows x 1 columns]

In [ ]:
#Data Duplicate
duplicates = df.duplicated(subset='full_text')
(duplicates.sum())

np.int64(46)

In [ ]:
duplicate_rows = df[df.duplicated(subset='full_text', keep=False)]
(duplicate_rows)

                                              full_text
836                               Sukseskan program MBG
837                               Sukseskan program MBG
3720                               SAATNYA TOLAK MBG...
3725                               SAATNYA TOLAK MBG...
4159   Anak kenyang belajar pun tenang. MBG bukan se...
...                                                 ...
6606  STAF Khusus Kepala Badan Gizi Nasional (BGN) b...
6637  Bersama Dukung Program MBG #FaktaIndonesia #Ma...
6951  Bersama Dukung Program MBG #FaktaIndonesia #Ma...
7525  Inilah sebabnya gue prefer pendidikan gratis d...
7526  Inilah sebabnya gue prefer pendidikan gratis d...

[92 rows x 1 columns]

In [ ]:
df.drop_duplicates(subset='full_text', inplace=True)
(df.count())
df

                                              full_text
0           @DS_yantie Lah itu MBG apakabar??? Pak pak
1     MBG anak sehat Indonesia hebat #FaktaIndonesia...
2     Pentingnya program MBG untuk masa depan #Fakta...
3     MBG adalah langkah nyata membangun generasi se...
4     @komaria_cocom MBG anakku loh kak bikin ngelus...
...                                                 ...
7799  Naahh!! Dengan adanya program MBG anak-anak ga...
7800  @ranie__14 @endahm7 @Dandhy_Laksono yang dimak...
7801  Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...
7802  @txtdrimedia Yg dikasih MBG jutaan siswa kalan...
7803            mbg yg baru jalan blm ada setaun itu..?

[7758 rows x 1 columns]

In [ ]:
#Cleaning Data
def cleaning(text):
    text = re.sub(r'@\w+(?:_\w+)*\b', '', text) # menghapus mention
    text = re.sub(r'#\w+', '', text) # menghapus hashtag
    text = re.sub(r'RT[\s]', '', text) # menghapus RT
    text = re.sub(r"http\S+", '', text) # menghapus link
    text = re.sub(r'[0-9]+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]', '', text) # menghapus karakter selain huruf dan angka
    text = re.sub(r'r\$\w*', '', text) # menghapus karakter dollar '$'
    text = re.sub(r'[^\x00-\x7F]+', '', text) # menghapus emoji dan karakter non-ASCII
    text = re.sub(r'[^A-Za-z0-9 ]', '', text) # membersihkan teks dengan menghapus semua karakter selain huruf, angka, dan spasi.
    text = re.sub(r'\s+', ' ', text).strip() # mengganti multiple spaces ke single spaces
    text = text.translate(str.maketrans('', '', string.punctuation)) # menghapus semua tanda baca
    text = text.strip(' ') # menghapus karakter spasi dari kiri dan kanan teks
    return text

df['text_clean']= df['full_text'].apply(cleaning)

In [ ]:
df

,full_text,text_clean
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...
...,...,...
7799,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...
7800,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...
7801,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...
7802,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...
7803,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu

# Case Folding

In [ ]:
#CaseFolding
def case_folding(text):
    text = text.lower()
    return text
df['text_casefolding'] = df['text_clean'].apply(case_folding)
df

,full_text,text_clean,text_casefolding
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...
...,...,...,...
7799,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...
7800,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...
7801,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...
7802,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...
7803,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu

In [ ]:
display(df[['text_clean', 'text_casefolding']])

,text_clean,text_casefolding
0,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak
1,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat
2,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan
3,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat
4,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...
...,...,...
7799,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...
7800,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...
7801,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...
7802,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...
7803,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu

# Tokenizing

In [ ]:
!pip install nltk
!pip install Sastrawi

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download data NLTK
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('all')
nltk.download('punkt_tab')

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.2)
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 8.3 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/maxent_treebank_pos_tagger_tab.zip.
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mock_corpus.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt_tab.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets_json.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
df['text_token'] = df['text_casefolding'].apply(lambda x: word_tokenize(x))
df

,full_text,text_clean,text_casefolding,text_token
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]"
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]"
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]"
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener..."
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b..."
...,...,...,...,...
7799,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...,"[naahh, dengan, adanya, program, mbg, anakanak..."
7800,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...,"[yang, dimaksudkan, itu, program, mbg, di, dae..."
7801,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...,"[pertemuan, prabowomacron, bahas, isu, mbg, hi..."
7802,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd..."
7803,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]"

In [ ]:
display(df[['text_casefolding', 'text_token']])

,text_casefolding,text_token
0,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]"
1,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]"
2,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]"
3,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener..."
4,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b..."
...,...,...
7799,naahh dengan adanya program mbg anakanak gaj p...,"[naahh, dengan, adanya, program, mbg, anakanak..."
7800,yang dimaksudkan itu program mbg di daerah yan...,"[yang, dimaksudkan, itu, program, mbg, di, dae..."
7801,pertemuan prabowomacron bahas isu mbg hingga a...,"[pertemuan, prabowomacron, bahas, isu, mbg, hi..."
7802,yg dikasih mbg jutaan siswa kalangan sdsma buk...,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd..."
7803,mbg yg baru jalan blm ada setaun itu,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]"

# Normalisasi

In [ ]:
# Baca file CSV yang berisi kolom slang dan formal
# Load kamus slang dari file CSV
slang_dictionary1 = pd.read_excel('/content/drive/MyDrive/Skripsi/kamus_alay.xlsx')
slang_dictionary2 = pd.read_csv('/content/drive/MyDrive/Skripsi/kamus-normalisasi.csv')

# Gabungkan kamus slang
slang_dict1 = pd.Series(slang_dictionary1['kata_baku'].values,index=slang_dictionary1['tidak_baku']).to_dict()
slang_dict2 = pd.Series(slang_dictionary2['kata_baku'].values,index=slang_dictionary2['tidak_baku']).to_dict()

slang_dict = {**slang_dict1, **slang_dict2}

# Fungsi normalisasi
def normalisasi(text):
  if text is not None:
    hasil = [slang_dict[word] if word in slang_dict else word for word in text]
    return hasil
  else:
    return []

df['text_normalize'] = df['text_token'].apply(normalisasi)
df

,full_text,text_clean,text_casefolding,text_token,text_normalize
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]","[lah, itu, mbg, apakabar, pak, pak]"
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]"
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]"
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener..."
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b...","[mbg, anakku, kok, kak, buat, ngelus, dada, bu..."
...,...,...,...,...,...
7799,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...,"[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, dengan, adanya, program, mbg, anakanak..."
7800,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...,"[yang, dimaksudkan, itu, program, mbg, di, dae...","[yang, dimaksudkan, itu, program, mbg, di, dae..."
7801,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...,"[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, hi..."
7802,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd...","[yang, dikasih, mbg, jutaan, siswa, kalangan, ..."
7803,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]","[mbg, yang, baru, jalan, belum, ada, setaun, itu]"

In [ ]:
display(df[['text_token', 'text_normalize']])

,text_token,text_normalize
0,"[lah, itu, mbg, apakabar, pak, pak]","[lah, itu, mbg, apakabar, pak, pak]"
1,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]"
2,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]"
3,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener..."
4,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b...","[mbg, anakku, kok, kak, buat, ngelus, dada, bu..."
...,...,...
7799,"[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, dengan, adanya, program, mbg, anakanak..."
7800,"[yang, dimaksudkan, itu, program, mbg, di, dae...","[yang, dimaksudkan, itu, program, mbg, di, dae..."
7801,"[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, hi..."
7802,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd...","[yang, dikasih, mbg, jutaan, siswa, kalangan, ..."
7803,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]","[mbg, yang, baru, jalan, belum, ada, setaun, itu]"

# Stopword Removal

In [ ]:
# get stopword indonesia
list_stopwords = stopwords.words('indonesian')

# append additional stopword
list_stopwords.extend(['klo','kalo', 'amp', 'biar', 'bikin', 'bilang',
                       'gak', 'ga', 'krn', 'nya', 'nih', 'sih',
                       'si', 'tau', 'tdk', 'tuh', 'utk', 'ya',
                       'jd', 'jgn', 'sdh', 'aja', 'n', 't',
                       'nyg', 'hehe', 'pen', 'u', 'nan', 'loh', 'rt',
                       '&amp', 'yah', 'gileee', 'fck', 'up', 'ah'])

# read xls stopword using pandas, specifying the sheet name and using the correct reader
txt_stopword = pd.read_table('/content/drive/MyDrive/Skripsi/stopwords-indonesia.txt', header=None, names=['stopwords'])

# convert stopword string to list & append additional stopword
list_stopwords.extend(txt_stopword['stopwords'][0].split(' '))

# convert list to dictionary (set for faster lookup)
list_stopwords = set(list_stopwords)

#remove stopword pada list token
def stopwords_removal(words):
    return [word for word in words if word not in list_stopwords]

df['text_stopwords'] = df['text_normalize'].apply(stopwords_removal)
df

,full_text,text_clean,text_casefolding,text_token,text_normalize,text_stopwords
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]","[lah, itu, mbg, apakabar, pak, pak]","[mbg, apakabar]"
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]"
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]","[pentingnya , program, mbg]"
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, langkah, nyata, membangun, generasi, sehat]"
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b...","[mbg, anakku, kok, kak, buat, ngelus, dada, bu...","[mbg, anakku, kak, ngelus, dada, salak, susu, ..."
...,...,...,...,...,...,...
7799,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...,"[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, program, mbg, anakanak, gaj, membeli, ..."
7800,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...,"[yang, dimaksudkan, itu, program, mbg, di, dae...","[yang, dimaksudkan, itu, program, mbg, di, dae...","[program, mbg, daerah, terpapar, pencemaran, l..."
7801,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...,"[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, al..."
7802,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd...","[yang, dikasih, mbg, jutaan, siswa, kalangan, ...","[dikasih, mbg, jutaan, siswa, kalangan, sdsma,..."
7803,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]","[mbg, yang, baru, jalan, belum, ada, setaun, itu]","[mbg, jalan, setaun]"

In [ ]:
display(df[['text_normalize', 'text_stopwords']])

,text_normalize,text_stopwords
0,"[lah, itu, mbg, apakabar, pak, pak]","[mbg, apakabar]"
1,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]"
2,"[pentingnya , program, mbg, untuk, masa, depan]","[pentingnya , program, mbg]"
3,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, langkah, nyata, membangun, generasi, sehat]"
4,"[mbg, anakku, kok, kak, buat, ngelus, dada, bu...","[mbg, anakku, kak, ngelus, dada, salak, susu, ..."
...,...,...
7799,"[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, program, mbg, anakanak, gaj, membeli, ..."
7800,"[yang, dimaksudkan, itu, program, mbg, di, dae...","[program, mbg, daerah, terpapar, pencemaran, l..."
7801,"[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, al..."
7802,"[yang, dikasih, mbg, jutaan, siswa, kalangan, ...","[dikasih, mbg, jutaan, siswa, kalangan, sdsma,..."
7803,"[mbg, yang, baru, jalan, belum, ada, setaun, itu]","[mbg, jalan, setaun]"

# Stemming

In [ ]:
!pip install swifter

Collecting swifter
  Downloading swifter-1.4.0.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 13.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from swifter) (2.2.2)
Requirement already satisfied: psutil>=5.6.6 in /usr/local/lib/python3.12/dist-packages (from swifter) (5.9.5)
Requirement already satisfied: dask>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]>=2.10.0->swifter) (2025.9.1)
Requirement already satisfied: tqdm>=4.33.0 in /usr/local/lib/python3.12/dist-packages (from swifter) (4.67.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (0.12.1)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]>=2.10.0->swifter) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->swifter) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->swifter) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->swifter) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->swifter) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->swifter) (1.17.0)
Building wheels for collected packages: swifter
  Building wheel for swifter (setup.py) ... done
  Created wheel for swifter: filename=swifter-1.4.0-py3-none-any.whl size=16505 sha256=12065167d1b55c1ba789a882916ebd12c200145deecf2540e65aae496917ebd5
  Stored in directory: /root/.cache/pip/wheels/d9/31/ff/ff51141a088571a9f672449e5aad5ea8bb35ca5d95ba135f30
Successfully built swifter
Installing collected packages: swifter
Successfully installed swifter-1.4.0

In [ ]:
# Aktifkan integrasi tqdm dengan pandas
tqdm.pandas()
# Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter
# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stemmed
def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict = {}

for document in df['text_token']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '

print(len(term_dict))
print("------------------------")

for term in term_dict:
    term_dict[term] = stemmed_wrapper(term)
    print(term,":" ,term_dict[term])

print(term_dict)
print("------------------------")


# apply stemmed term to dataframe
def get_stemmed_term(document):
    return [term_dict[term] for term in document]

df['text_stemmed'] = df['text_token'].apply(get_stemmed_term)

13464
------------------------
mbg : mbg
apakabar : apakabar
anak : anak
sehat : sehat
indonesia : indonesia
hebat : hebat
program : program
langkah : langkah
nyata : nyata
membangun : bangun
generasi : generasi
anakku : anak
kak : kak
ngelus : ngelus
dada : dada
salak : salak
susu : susu
uht : uht
kotak : kotak
biskuit : biskuit
regal : regal
bungkus : bungkus
telor : telor
fokus : fokus
belajar : ajar
pondasi : pondasi
cerah : cerah
dukung : dukung
mengomong : omong
bersyukur : syukur
pencetus : cetus
nanem : nanem
sawit : sawit
menyebabkan : sebab
bencana : bencana
alam : alam
astagfirullah : astagfirullah
adzim : adzim
benaran : benar
rezim : rezim
anti : anti
kritik : kritik
nirempati : nirempati
bidang : bidang
terima : terima
gagal : gagal
noh : noh
parah : parah
wkwkw : wkwkw
konsisten : konsisten
tone : tone
deaf : deaf
gara-gara : gara-gara
warung : warung
makan : makan
sepi : sepi
sekolah : sekolah
beli : beli
kemarin : kemarin
langsung : langsung
langganan : langgan
jatah : jatah
diambil : ambil
dibawa : bawa
pulang : pulang
libur : libur
bpk : bpk
baiknya : baik
pemerintah : perintah
buang : buang
anggaran : anggar
iya : iya
ih : ih
gila : gila
suruh : suruh
ambil : ambil
lihat : lihat
menu : menu
miris : miris
pikiranku : pikir
makanan : makan
healthy : healthy
gizi : gizi
seimbang : imbang
gitu : gitu
mengerti : erti
kutemukan : temu
katsu : katsu
burger : burger
terserah : serah
no : no
words : words
pejabat : jabat
sinting : sinting
bangsa : bangsa
penuh : penuh
syukur : syukur
tiwel : tiwel
getuk : getuk
nasi : nasi
jagung : jagung
blt : blt
nama : nama
jabatannya : jabat
aneh : aneh
negara : negara
maksud : maksud
tujuan : tuju
tugas : tugas
badan : badan
kerja : kerja
dipaksakan : paksa
dilaksanakan : laksana
siswa : siswa
daging : daging
lain-lain : lain
sisi : sisi
positif : positif
negatif : negatif
enak : enak
ribu : ribu
permurid : murid
murid : murid
Cuma : cuma
harga : harga
pokok : pokok
pasar : pasar
naikkk : naikkk
mahal : mahal
keluarganya : keluarga
keracunan : racun
diam : diam
nder : nder
teman : teman
sejahtera : sejahtera
banget : banget
dihitung : hitung
gaka : gaka
minggu : minggu
meluncur : luncur
sungguh : sungguh
lucu : lucu
programnya : program
jalan : jalan
tujuannya : tuju
mengharap : harap
orang : orang
termotivasi : motivasi
eksperimen : eksperimen
lahiran : lahir
diretur : retur
bayi : bayi
cari : cari
catering : catering
yos : yos
tanggapi : tanggap
angin : angin
presiden : presiden
sono : sono
ganti : ganti
bubar : bubar
habis : habis
cucu : cucu
anaknya : anak
gasik : gasik
goblok : goblok
reply : reply
menarik : tarik
bukti : bukti
matang : matang
direncanakan : rencana
beda : beda
sppg : sppg
budget : budget
kah : kah
kemasan : kemas
manggis : manggis
kacang : kacang
polong : polong
telur : telur
ngajukan : ngajukan
surat : surat
menerima : terima
repot : repot
ngurusinnya : ngurusinnya
setara : tara
stop : stop
setuju : tuju
kasih : kasih
tua : tua
seminggu : minggu
dikasih : kasih
xrb : xrb
korupsi : korupsi
jateng : jateng
dampak : dampak
omgbukan : omgbukan
hrskah : hrskah
berdiam : diam
membiarkan : biar
menunggu : tunggu
sisa : sisa
kehancurannya : hancur
tuhan : tuhan
beserta : serta
hambanya : hamba
berjuang : juang
kemuliaan : mulia
kebatilan : batil
kerusakan : rusa
timbulkan : timbul
trilyun : trilyun
terbuang : buang
hutan : hutan
Papua : papua
Selatan : selatan
dibabat : babat
kelapa : kelapa
sawitampfood : sawitampfood
estate : estate
penanganan : tangan
sumatra : sumatra
ala : ala
kadarnya : kadar
pemilu : milu
i : i
think : think
can : can
afford : afford
another : another
years : years
him : him
investasi : investasi
jangka : jangka
kualitas : kualitas
sumber : sumber
daya : daya
manusia : manusia
sinergi : sinergi
koperasi : koperasi
desa : desa
membuka : buka
peluang : peluang
meningkatkan : tingkat
pendapatan : dapat
pelaku : laku
usaha : usaha
lokal : lokal
pemberi : beri
tahuan : tahu
belatung : belatung
kumpulin : kumpulin
belatungnya : belatung
ikeu : ikeu
tanziha : tanziha
bersykur : bersykur
hadir : hadir
melayani : layan
anakanak : anakanak
sesuai : sesuai
visi : visi
misi : misi
memenuhi : penuh
hamil : hamil
menyusui : susu
balita : balita
pemenuhan : penuh
siang : siang
persis : persis
kayak : kayak
merasakan : rasa
baca : baca
berita : berita
adek : adek
memaksakan : paksa
diblng : diblng
puasa : puasa
jeda : jeda
dululah : dululah
korupsinya : korupsi
maruk : maruk
gatel : gatel
kali : kali
sehari : hari
my : my
bojo : bojo
gweh : gweh
guru : guru
mengakui : aku
pernyataan : nyata
jam : jam
istirahat : istirahat
dihabiskan : habis
memotong : potong
pelajaran : ajar
disiplin : disiplin
sumpah : sumpah
dati : dati
gara : gara
distribusi : distribusi
kesentuh : sentuh
kpk : kpk
wilayah : wilayah
sugapa : sugapa
kabupaten : kabupaten
intan : intan
jaya : jaya
spesial : spesial
didampingi : damping
kementrian : tri
pertahanan : tahan
panglima : panglima
komando : komando
gabungan : gabung
pangkogabwilhan : pangkogabwilhan
iii : iii
letjen : letjen
Tentara : tentara
Nasional : nasional
Indonesia : indonesia
Bambang : bambang
trisnohadi : trisnohadi
gaak : gaak
pertemuan : temu
rutin : rutin
bingkisan : bingkis
amplop : amplop
tim : tim
dapur : dapur
tur : tur
gratis : gratis
semenggiurkan : giur
sebanding : banding
eh : eh
kebanyakwn : kebanyakwn
otak : otak
dipakai : pakai
tinggal : tinggal
hapus : hapus
berjalan : jalan
alirkannya : alir
penerima : terima
manfaat : manfaat
jjr : jjr
alirkan : alir
jalanan : jalan
maaf : maaf
chatku : chatku
typo : typo
menulis : tulis
datapun : data
prabowo : prabowo
paket : paket
dibagi : bagi
terbantu : bantu
jalas : jalas
ladang : ladang
basah : basah
koruptor : koruptor
bmg : bmg
bisnis : bisnis
nilai : nilai
drop : drop
hidup : hidup
berkat : berkat
pas : pas
dibagiin : dibagiin
kece : kece
narasi : narasi
dipaksa : paksa
utama : utama
doang : doang
bergizi : gizi
amburadul : amburadul
coma : coma
cops : cops
pokoknya : pokok
bahas : bahas
disamber : disamber
gapeduli : gapeduli
konteksnya : konteks
ratus : ratus
perak : perak
zamanku : zaman
peogram : peogram
pembiasaan : biasa
literasi : literasi
menit : menit
gurumapelnya : gurumapelnya
santai : santai
cuman : cuman
pembelajaran : ajar
habislah : habis
jamnya : jam
masuk : masuk
kelas : kelas
untungnya : untung
pengusaha : usaha
jualan : jual
maksa : maksa
ramadhan : ramadhan
apanya : apa
modal : modal
uang : uang
rakyat : rakyat
dapetnya : dapetnya
kejorokan : jorok
dibilang : bilang
jadikan : jadi
pusing : pusing
mun : mun
aya : aya
keneh : keneh
nyelilit : nyelilit
kosong : kosong
mobil : mobil
konsen : konsen
diajak : ajak
lariii : lariii
kadang : kadang
semuannya : semu
setor : setor
foto : foto
bukakan : buka
bereskan : beres
ribet : ribet
bantuin : bantuin
paud : paud
ngomong-ngomong : ngomong-ngomong
pakar : pakar
ahli : ahli
menduga : duga
bau : bau
amis : amis
dirapel : rapel
bini : bini
harap : harap
maklum : maklum
profitable : profitable
menggiurkan : giur
rupiah : rupiah
supervisi : supervisi
koreksi : koreksi
audit : audit
oversee : oversee
dpr : dpr
menyusahkan : susah
oh : oh
wkwkwkwkwkwkkwkwkwwkkwwj : wkwkwkwkwkwkkwkwkwwkkwwj
duitnya : duit
jtrakyat : jtrakyat
PKH : pkh
pip : pip
kis : kis
perusahaan : usaha
kesehatan : sehat
error : error
otaknya : otak
riweuh : riweuh
rapor : rapor
membagikan : bagi
terpakai : pakai
kls : kls
bagiinnya : bagiinnya
tertib : tertib
ngaturmya : ngaturmya
cepat : cepat
kotor : kotor
mengajar : ajar
solusinya : solusi
terdengar : dengar
tolol : tolol
simpanse : simpanse
biarpun : biarpun
sebentar : sebentar
info : info
loker : loker
buzzer : buzzer
darto : darto
helm : helm
judol : judol
meredup : redup
terbitlah : terbit
oke : oke
mencari : cari
dasarbarang : dasarbarang
busuk : busuk
coba : coba
cek : cek
kegiatan : giat
pemborosan : boros
diduga : duga
keserakahan : serakah
mencairkan : cair
dana : dana

KeyboardInterrupt:

In [ ]:
# Normalisasi Negasi
#def convert_negasi(text):
#    text = re.sub("tidak ", 'tidak', text, flags=re.MULTILINE)
#    text = re.sub("jangan ", 'jangan', text, flags=re.MULTILINE)
#    text = re.sub("belum ", 'belum', text, flags=re.MULTILINE)
#    text = re.sub("bukan ", 'bukan', text, flags=re.MULTILINE)
#    text = re.sub("tanpa ", 'tanpa', text, flags=re.MULTILINE)
#    text = re.sub("bukanlah ", 'bukanlah', text, flags=re.MULTILINE)
#    text = re.sub("tak ", 'tak', text, flags=re.MULTILINE)
#    text = re.sub("anti ", 'anti', text, flags=re.MULTILINE)
#    return text
#df['text_stemmed']= df['text_stemmed'].apply(lambda x: convert_negasi(x))
#df

# Data Labeling

In [ ]:
!pip install scikit-learn
from sklearn.metrics import accuracy_score
from google.colab import files

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
# Function to ensure all elements in a list are strings and handle potential non-list entries
def clean_and_join(word_list):
    if not isinstance(word_list, list):
        return '' # Return empty string if it's not a list (e.g., NaN)
    cleaned_list = []
    for item in word_list:
        if pd.isna(item):
            cleaned_list.append('') # Replace NaN with empty string
        else:
            cleaned_list.append(str(item))
    return ' '.join(cleaned_list).strip()

# Apply the cleaning and joining function to create the 'text' column
df['text'] = df['text_stopwords'].apply(clean_and_join)

# Drop any rows where 'text' might be empty or problematic after cleaning (optional, depending on desired behavior)
df.replace('', np.nan, inplace=True)
df.dropna(subset=['text'], inplace=True)
df = df.reset_index(drop=True)

display(df.head())

,full_text,text_clean,text_casefolding,text_token,text_normalize,text_stopwords,text
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]","[lah, itu, mbg, apakabar, pak, pak]","[mbg, apakabar]",mbg apakabar
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]",mbg anak sehat indonesia hebat
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]","[pentingnya , program, mbg]",pentingnya program mbg
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, langkah, nyata, membangun, generasi, sehat]",mbg langkah nyata membangun generasi sehat
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b...","[mbg, anakku, kok, kak, buat, ngelus, dada, bu...","[mbg, anakku, kak, ngelus, dada, salak, susu, ...",mbg anakku kak ngelus dada salak susu uht kota...

In [ ]:
print(f"Original dataset size: {len(df)}")

Original dataset size: 7755

In [ ]:
duplicates = df.duplicated(subset='text')
(duplicates.sum())

np.int64(393)

In [ ]:
duplicate_rows = df[df.duplicated(subset='text', keep=False)]
(duplicate_rows)

,full_text,text_clean,text_casefolding,text_token,text_normalize,text_stopwords,text
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]",mbg anak sehat indonesia hebat
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]","[pentingnya , program, mbg]",pentingnya program mbg
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, langkah, nyata, membangun, generasi, sehat]",mbg langkah nyata membangun generasi sehat
5,MBG buat anak lebih fokus belajar #MakanBergiz...,MBG buat anak lebih fokus belajar,mbg buat anak lebih fokus belajar,"[mbg, buat, anak, lebih, fokus, belajar]","[mbg, buat, anak, lebih, fokus, belajar]","[mbg, anak, fokus, belajar]",mbg anak fokus belajar
6,MBG Pondasi masa depan cerah #MakanBergiziGrat...,MBG Pondasi masa depan cerah,mbg pondasi masa depan cerah,"[mbg, pondasi, masa, depan, cerah]","[mbg, pondasi, masa, depan, cerah]","[mbg, pondasi, cerah]",mbg pondasi cerah
...,...,...,...,...,...,...,...
7481,Organisasi pengusaha di Prancis Mouvement des ...,Organisasi pengusaha di Prancis Mouvement des ...,organisasi pengusaha di prancis mouvement des ...,"[organisasi, pengusaha, di, prancis, mouvement...","[organisasi, pengusaha, di, prancis, mouvement...","[organisasi, pengusaha, prancis, mouvement, de...",organisasi pengusaha prancis mouvement des ent...
7618,TNI lahir dari rakyat bekerja untuk rakyat dan...,TNI lahir dari rakyat bekerja untuk rakyat dan...,tni lahir dari rakyat bekerja untuk rakyat dan...,"[tni, lahir, dari, rakyat, bekerja, untuk, rak...","[Tentara Nasional Indonesia , Lahir , dari, ...","[Tentara Nasional Indonesia , Lahir , rakyat...",Tentara Nasional Indonesia Lahir rakyat ra...
7619,TNI lahir dari rakyat bekerja untuk rakyat dan...,TNI lahir dari rakyat bekerja untuk rakyat dan...,tni lahir dari rakyat bekerja untuk rakyat dan...,"[tni, lahir, dari, rakyat, bekerja, untuk, rak...","[Tentara Nasional Indonesia , Lahir , dari, ...","[Tentara Nasional Indonesia , Lahir , rakyat...",Tentara Nasional Indonesia Lahir rakyat ra...
7630,@trsYUNA Dapet MBG,Dapet MBG,dapet mbg,"[dapet, mbg]","[dapat, mbg]",[mbg],mbg
7662,gue ga dapet MBG naik tuh 3cm,gue ga dapet MBG naik tuh cm,gue ga dapet mbg naik tuh cm,"[gue, ga, dapet, mbg, naik, tuh, cm]","[saya, enggak, dapat, mbg, naik, itu, Cuma]","[mbg, Cuma]",mbg Cuma

In [ ]:
df.drop_duplicates(subset='text', inplace=True)
(df.count())
df

,full_text,text_clean,text_casefolding,text_token,text_normalize,text_stopwords,text
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"[lah, itu, mbg, apakabar, pak, pak]","[lah, itu, mbg, apakabar, pak, pak]","[mbg, apakabar]",mbg apakabar
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]","[mbg, anak, sehat, indonesia, hebat]",mbg anak sehat indonesia hebat
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"[pentingnya, program, mbg, untuk, masa, depan]","[pentingnya , program, mbg, untuk, masa, depan]","[pentingnya , program, mbg]",pentingnya program mbg
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, adalah, langkah, nyata, membangun, gener...","[mbg, langkah, nyata, membangun, generasi, sehat]",mbg langkah nyata membangun generasi sehat
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"[mbg, anakku, loh, kak, bikin, ngelus, dada, b...","[mbg, anakku, kok, kak, buat, ngelus, dada, bu...","[mbg, anakku, kak, ngelus, dada, salak, susu, ...",mbg anakku kak ngelus dada salak susu uht kota...
...,...,...,...,...,...,...,...
7750,Naahh!! Dengan adanya program MBG anak-anak ga...,Naahh Dengan adanya program MBG anakanak gaj p...,naahh dengan adanya program mbg anakanak gaj p...,"[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, dengan, adanya, program, mbg, anakanak...","[naahh, program, mbg, anakanak, gaj, membeli, ...",naahh program mbg anakanak gaj membeli makanan...
7751,@ranie__14 @endahm7 @Dandhy_Laksono yang dimak...,yang dimaksudkan itu program MBG di daerah yan...,yang dimaksudkan itu program mbg di daerah yan...,"[yang, dimaksudkan, itu, program, mbg, di, dae...","[yang, dimaksudkan, itu, program, mbg, di, dae...","[program, mbg, daerah, terpapar, pencemaran, l...",program mbg daerah terpapar pencemaran logam b...
7752,Pertemuan Prabowo-Macron Bahas Isu MBG hingga ...,Pertemuan PrabowoMacron Bahas Isu MBG hingga A...,pertemuan prabowomacron bahas isu mbg hingga a...,"[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, hi...","[pertemuan, prabowomacron, bahas, isu, mbg, al...",pertemuan prabowomacron bahas isu mbg alutsista
7753,@txtdrimedia Yg dikasih MBG jutaan siswa kalan...,Yg dikasih MBG jutaan siswa kalangan SDSMA Buk...,yg dikasih mbg jutaan siswa kalangan sdsma buk...,"[yg, dikasih, mbg, jutaan, siswa, kalangan, sd...","[yang, dikasih, mbg, jutaan, siswa, kalangan, ...","[dikasih, mbg, jutaan, siswa, kalangan, sdsma,...",dikasih mbg jutaan siswa kalangan sdsma bukti ...
7754,mbg yg baru jalan blm ada setaun itu..?,mbg yg baru jalan blm ada setaun itu,mbg yg baru jalan blm ada setaun itu,"[mbg, yg, baru, jalan, blm, ada, setaun, itu]","[mbg, yang, baru, jalan, belum, ada, setaun, itu]","[mbg, jalan, setaun]",mbg jalan setaun

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7362 entries, 0 to 7754
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   full_text         7362 non-null   object
 1   text_clean        7362 non-null   object
 2   text_casefolding  7362 non-null   object
 3   text_token        7362 non-null   object
 4   text_normalize    7362 non-null   object
 5   text_stopwords    7362 non-null   object
 6   text              7362 non-null   object
dtypes: object(7)
memory usage: 460.1+ KB

In [ ]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch
import ast

# 1. Load Model & Tokenizer
model_name = "mdhugol/indonesia-bert-sentiment-classification"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Sinkronisasi mapping (0:Positif, 1:Netral, 2:Negatif)
model.config.id2label = {0: "Positif", 1: "Netral", 2: "Negatif"}
model.config.label2id = {"Positif": 0, "Netral": 1, "Negatif": 2}

# 2. Inisialisasi pipeline
device = 0 if torch.cuda.is_available() else -1
classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=device)

labels = []
scores = []

# 3. Prediksi per baris menggunakan kolom 'text_stemmed'
print(f"Memulai pelabelan dataset...")
for text in df['text'].astype(str).tolist():
    result = classifier(text, truncation=True)

    if result:
        labels.append(result[0]['label'])
        scores.append(result[0]['score'])
    else:
        labels.append('Netral')
        scores.append(0)

# 4. Mapping balik dari teks ke angka (0, 1, 2)
label_map = {"Positif": 0, "Netral": 1, "Negatif": 2}

df["Label_ID"] = [label_map[label] for label in labels]
df["Confidence_Score"] = scores

# 5. Kolom nama sentimen
df['Sentimen'] = labels

print("Pelabelan selesai.")
display(df[['text', 'Sentimen', 'Label_ID', 'Confidence_Score']].head())

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: mdhugol/indonesia-bert-sentiment-classification
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

Memulai pelabelan dataset...

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Pelabelan selesai.

,text,Sentimen,Label_ID,Confidence_Score
0,mbg apakabar,Negatif,2,0.503783
1,mbg anak sehat indonesia hebat,Positif,0,0.995272
2,pentingnya program mbg,Netral,1,0.665221
3,mbg langkah nyata membangun generasi sehat,Positif,0,0.528011
4,mbg anakku kak ngelus dada salak susu uht kota...,Netral,1,0.990892

In [ ]:
print(df['Sentimen'].value_counts())

Sentimen
Negatif    3974
Netral     1985
Positif    1403
Name: count, dtype: int64

In [ ]:
data_prep = df.to_csv("data_prepro.csv", index=False)

In [ ]:
data_prep = pd.read_csv("data_prepro.csv")
display(data_prep.head())

,full_text,text_clean,text_casefolding,text_token,text_normalize,text_stopwords,text,Label_ID,Confidence_Score,Sentimen
0,@DS_yantie Lah itu MBG apakabar??? Pak pak,Lah itu MBG apakabar Pak pak,lah itu mbg apakabar pak pak,"['lah', 'itu', 'mbg', 'apakabar', 'pak', 'pak']","['lah', 'itu', 'mbg', 'apakabar', 'pak', 'pak']","['mbg', 'apakabar']",mbg apakabar,2,0.503783,Negatif
1,MBG anak sehat Indonesia hebat #FaktaIndonesia...,MBG anak sehat Indonesia hebat,mbg anak sehat indonesia hebat,"['mbg', 'anak', 'sehat', 'indonesia', 'hebat']","['mbg', 'anak', 'sehat', 'indonesia', 'hebat']","['mbg', 'anak', 'sehat', 'indonesia', 'hebat']",mbg anak sehat indonesia hebat,0,0.995272,Positif
2,Pentingnya program MBG untuk masa depan #Fakta...,Pentingnya program MBG untuk masa depan,pentingnya program mbg untuk masa depan,"['pentingnya', 'program', 'mbg', 'untuk', 'mas...","['pentingnya ', 'program', 'mbg', 'untuk', 'm...","['pentingnya ', 'program', 'mbg']",pentingnya program mbg,1,0.665221,Netral
3,MBG adalah langkah nyata membangun generasi se...,MBG adalah langkah nyata membangun generasi sehat,mbg adalah langkah nyata membangun generasi sehat,"['mbg', 'adalah', 'langkah', 'nyata', 'membang...","['mbg', 'adalah', 'langkah', 'nyata', 'membang...","['mbg', 'langkah', 'nyata', 'membangun', 'gene...",mbg langkah nyata membangun generasi sehat,0,0.528011,Positif
4,@komaria_cocom MBG anakku loh kak bikin ngelus...,MBG anakku loh kak bikin ngelus dada Buat hari...,mbg anakku loh kak bikin ngelus dada buat hari...,"['mbg', 'anakku', 'loh', 'kak', 'bikin', 'ngel...","['mbg', 'anakku', 'kok', 'kak', 'buat', 'ngelu...","['mbg', 'anakku', 'kak', 'ngelus', 'dada', 'sa...",mbg anakku kak ngelus dada salak susu uht kota...,1,0.990892,Netral

In [ ]:
from sklearn.model_selection import train_test_split

# Split data into training and validation sets (adjust test_size as needed)
train_df, val_df = train_test_split(data_prep, test_size=0.2, random_state=42)

print("Training set shape:", train_df.shape)
print("Validation set shape:", val_df.shape)

Training set shape: (5889, 10)
Validation set shape: (1473, 10)

In [ ]:
from transformers import Trainer, TrainingArguments, AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding, EarlyStoppingCallback
from datasets import Dataset
import torch
import os

# ======================================================
# 1. GUNAKAN MODEL YANG LEBIH STABIL (SOLUSI UTAMA)
# ======================================================
# Kita ganti ke model benchmark standar agar tidak ada error LayerNorm
model_checkpoint = "indolem/indobert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# Pastikan jumlah label sesuai (3 Label)
# Mapping label agar sinkron
id2label = {0: "Negatif", 1: "Netral", 2: "Positif"}
label2id = {"Negatif": 0, "Netral": 1, "Positif": 2}

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

# ======================================================
# 2. PREPROCESSING (Sama seperti sebelumnya)
# ======================================================
def preprocess_data(examples):
    # Pastikan truncation=True dan max_length cukup
    tokenized_inputs = tokenizer(examples['text_stopwords'], truncation=True, max_length=128)
    tokenized_inputs['labels'] = examples['Label_ID']
    return tokenized_inputs

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

train_dataset = train_dataset.map(preprocess_data, batched=True)
val_dataset = val_dataset.map(preprocess_data, batched=True)

# Bersihkan kolom tidak perlu
cols_to_keep = ['input_ids', 'attention_mask', 'labels', 'token_type_ids'] # token_type_ids perlu untuk BERT
cols_to_remove = [c for c in train_dataset.column_names if c not in cols_to_keep]
train_dataset = train_dataset.remove_columns(cols_to_remove)
val_dataset = val_dataset.remove_columns(cols_to_remove)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# ======================================================
# 3. TRAINING ARGUMENTS (Disesuaikan untuk stabilitas)
# ======================================================
training_args = TrainingArguments(
    output_dir='./results_fix',
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    learning_rate=1e-5,
    weight_decay=0.01,
    warmup_steps=100,
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    save_total_limit=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("Mulai Training Ulang...")
trainer.train()

# ======================================================
# 4. SOLUSI PERBAIKAN STATE DICT (PENTING!)
# ======================================================
print("Memperbaiki penamaan layer (beta/gamma -> bias/weight)...")

# Ambil bobot terbaik hasil training
best_model_weights = model.state_dict()
fixed_weights = {}

for key, value in best_model_weights.items():
    # Mengubah nama lama IndoLEM ke standar Transformers terbaru
    new_key = key.replace('LayerNorm.beta', 'LayerNorm.bias').replace('LayerNorm.gamma', 'LayerNorm.weight')
    fixed_weights[new_key] = value

# Masukkan kembali bobot yang sudah diperbaiki namanya ke dalam model
model.load_state_dict(fixed_weights)

# Simpan secara permanen
final_path = "./indobert_fine_tuned_final"
model.save_pretrained(final_path)
tokenizer.save_pretrained(final_path)

print(f"✅ Training Selesai & Model Berhasil Disimpan di: {final_path}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: indolem/indobert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/5889 [00:00<?, ? examples/s]

Map:   0%|          | 0/1473 [00:00<?, ? examples/s]

Mulai Training Ulang...

Error during conversion: AttributeError("'str' object has no attribute 'decode'")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Memperbaiki penamaan layer (beta/gamma -> bias/weight)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Training Selesai & Model Berhasil Disimpan di: ./indobert_fine_tuned_final

In [ ]:
import torch
from transformers import pipeline

# ==========================================
# 1. PERBAIKAN STATE DICT (WAJIB SEBELUM PREDIKSI)
# ==========================================
print("Menyelaraskan bobot model...")
best_weights = model.state_dict()
fixed_weights = {}
for key, value in best_weights.items():
    new_key = key.replace('LayerNorm.beta', 'LayerNorm.bias').replace('LayerNorm.gamma', 'LayerNorm.weight')
    fixed_weights[new_key] = value

model.load_state_dict(fixed_weights)

# Sinkronisasi Mapping (Sesuaikan dengan Label_ID awalmu)
model.config.id2label = {0: "Positif", 1: "Netral", 2: "Negatif"}
model.config.label2id = {"Positif": 0, "Netral": 1, "Negatif": 2}

# ==========================================
# 2. INISIALISASI PIPELINE PREDIKSI
# ==========================================
device = 0 if torch.cuda.is_available() else -1
fine_tuned_classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=device)

updated_labels = []
updated_scores = []

print("Memulai prediksi dataset dengan model hasil fine-tune...")
for text in df['text_stopwords'].astype(str).tolist():
    result = fine_tuned_classifier(text, truncation=True)

    if result:
        updated_labels.append(result[0]['label'])
        updated_scores.append(result[0]['score'])
    else:
        updated_labels.append('Netral')
        updated_scores.append(0)

# ==========================================
# 3. PENYIMPANAN HASIL KE DATAFRAME
# ==========================================
# Pastikan mapping angka sesuai dengan standar yang kita pakai di awal (0=Pos, 1=Net, 2=Neg)
label_map = {"Positif": 0, "Netral": 1, "Negatif": 2}

df["Label_fine_tuned"] = [label_map[label] for label in updated_labels]
df["Confidence_fine_tuned"] = updated_scores
df['sentimen_fine_tuned'] = updated_labels

print("✅ Prediksi Selesai!")
display(df[['text_stopwords', 'sentimen_fine_tuned', 'Label_fine_tuned', 'Confidence_fine_tuned']].head())

Menyelaraskan bobot model...
Memulai prediksi dataset dengan model hasil fine-tune...
✅ Prediksi Selesai!

,text_stopwords,sentimen_fine_tuned,Label_fine_tuned,Confidence_fine_tuned
0,"[mbg, apakabar]",Negatif,2,0.935089
1,"[mbg, anak, sehat, indonesia, hebat]",Positif,0,0.947168
2,"[pentingnya , program, mbg]",Positif,0,0.542193
3,"[mbg, langkah, nyata, membangun, generasi, sehat]",Positif,0,0.905261
4,"[mbg, anakku, kak, ngelus, dada, salak, susu, ...",Netral,1,0.526549

In [ ]:
# Menampilkan jumlah masing-masing sentimen setelah fine-tuning
sentimen_fine_tuned_count = df['sentimen_fine_tuned'].value_counts()
print(sentimen_fine_tuned_count)

sentimen_fine_tuned
Negatif    4004
Netral     1866
Positif    1492
Name: count, dtype: int64

In [ ]:
# Save the DataFrame with the fine-tuned sentiment labels to a new CSV file
df.to_csv("data_prepro_labeled.csv", index=False)

In [ ]:
from google.colab import files

files.download("data_prepro_labeled.csv")